/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/Accordion.vue')['default']
    AddGroups: typeof import('./components/AddGroups.vue')['default']
    AddPages: typeof import('./components/AddPages.vue')['default']
    CommonConfirmDialog: typeof import('./components/common/ConfirmDialog.vue')['default']
    CommonDatatable: typeof import('./components/common/Datatable.vue')['default']
    CommonDialog: typeof import('./components/common/Dialog.vue')['default']
    CommonDrawer: typeof import('./components/common/Drawer.vue')['default']
    CommonMultiSelect: typeof import('./components/common/MultiSelect.vue')['default']
    CommonPagination: typeof import('./components/common/Pagination.vue')['default']
    CustomTable: typeof import('./components/custom-table.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
