/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/Accordion.vue')['default']
    AddGroups: typeof import('./components/AddGroups.vue')['default']
    AddPages: typeof import('./components/AddPages.vue')['default']
    ApplyPermissions: typeof import('./components/ApplyPermissions.vue')['default']
    CommonDatatable: typeof import('./components/common/Datatable.vue')['default']
    CommonPagination: typeof import('./components/common/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
